Serializing and Deserializing with Open API Spec
NREL-Sienna/PowerSystemsInvestmentsPortfolios.jl pull request #16
Opened 2024-10-03 21:32 UTC by jerrypotts

2025-02-03 22:06 UTC, rodrigomha commented
This should close #4

2025-03-17 21:23 UTC, rodrigomha commented
TODO: Review

- [ ] portfolio.jl
- [ ] serialization.jl
- [ ] financial data files
- [ ] Data Types review: Storage, Supply, Branches, HVDC

2025-03-17 22:36 UTC, rodrigomha commented on src/models/generated/MinimumCapacityRequirements.jl
>  - `name::String`: The technology name
This should say "The requirement name"

2025-03-17 22:39 UTC, rodrigomha commented on src/portfolio.jl
>  #TODO: Make immutable
Remove these TODO. We will not support unit systems, and change it to be immutable and see if it everything works

2025-03-17 22:42 UTC, rodrigomha commented on src/portfolio.jl
> +    # TODO: Fix/add validation
Open an issue for this validation and remove TODO

2025-03-17 22:45 UTC, rodrigomha commented on src/serialization.jl
>      # if !get_runchecks(portfolio)
Remove this comment of runchecks and open an issue for evaluating if we want to do checks on portfolios

2025-03-17 22:51 UTC, rodrigomha commented on test/data_5bus.jl
> +    IS.add_time_series!(p_5bus.data, t_pv2, ts_pv2_2024; year="2024", rep_day=1)
We need to have a method for add time series to a portfolio using kwargs that basically is a wrapper of this IS method.

2025-03-17 22:52 UTC, rodrigomha requested changes
Address specific comments

2025-03-19 13:57 UTC, jd-lara commented on Project.toml
> +HTTP = "cd3eb016-35fb-5094-929b-558a96fad6f3"
Why is HTTP required?

2025-03-19 14:00 UTC, jd-lara commented on src/definitions.jl
we should move these definitions to IS

2025-03-19 14:08 UTC, jd-lara commented on src/models/generated/CurtailableDemandSideTechnology.jl
> +        curtailment_cost::Vector{Float64}
why aren't we using a linear cost object here?

2025-03-19 14:11 UTC, jd-lara commented on src/models/generated/DemandsideTechnology.jl
> +        price_per_unit::Float64
what are these ramp percentages? These are operational parameters that don't exist in PowerSystems.jl

2025-03-19 14:36 UTC, jd-lara approved these changes
I have a couple of pending questions but the PR is already quite large and we will inevitable have to refine the fields as we continue to build the optimization tools

2025-03-21 17:07 UTC, rodrigomha approved these changes
LGTM

2025-03-21 17:07 UTC, merged